name: Michele Pio Fragasso
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
  sass_dir: _sass
  style: compressed

collections:
  projects:
    output: true
  furuta:
    output: true
  
